# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='coauthor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coauthored_books', to='bookshelf.Author', verbose_name='coauthor'),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookshelf.Author', verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookshelf.Publisher', verbose_name='publisher'),
        ),
    ]
